---

- name: ZOOKEEPER | JMX MONITORING | Create /etc/zookeeper/jmx_exporter_config.yml
  copy:
    src: jmx_exporter_config.yml
    dest: /etc/zookeeper/jmx_exporter_config.yml
    mode: "0640"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  notify: restart zookeeper

- name: ZOOKEEPER | JMX MONITORING | Ensure /opt/monitoring exists
  file:
    path: /opt/monitoring
    state: directory
    mode: "0755"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"

- name: ZOOKEEPER | JMX MONITORING | Fetch and install /opt/monitoring/jmx_prometheus_javaagent.jar
  get_url:
    url: "https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/{{ jmx_exporter_version }}/jmx_prometheus_javaagent-{{ jmx_exporter_version }}.jar"
    dest: /opt/monitoring/jmx_prometheus_javaagent.jar
    checksum: "{{ jmx_exporter_checksum }}"
    mode: "0640"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  notify: restart zookeeper
