---

- name: ZOOKEEPER | Create data path
  file:
    path: "{{ zookeeper_data_path }}"
    mode: 0760
    state: directory
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_user }}"

- name: ZOOKEEPER | Copy Daemon script
  template:
    src: "{{ zookeeper_service_template_path }}"
    dest: /lib/systemd/system/zookeeper.service
    mode: 0644
  notify: restart zookeeper

- name: ZOOKEEPER | Set JAVA_HOME
  lineinfile:
    path: /etc/profile
    regexp: '^export JAVA_HOME='
    line: 'export JAVA_HOME={{ zookeeper_java_home }}'

- name: ZOOKEEPER | Set PATH
  lineinfile:
    path: /etc/profile
    regexp: '^export PATH='
    line: 'export PATH=$JAVA_HOME/bin:$PATH'
